name: ci

on: push

jobs:
  pypi:
    name: Push to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: pipenv shell {0}
        run: |
          pipenv sync
          python3 setup.py sdist bdist_wheel
      - name: Push
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
